#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue May 12 23:43:15 -04 2020
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto b77cb173600240079fd1510a4d351ec8 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot Basys3_tb_behav xil_defaultlib.Basys3_tb -log elaborate.log"
xelab -wto b77cb173600240079fd1510a4d351ec8 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot Basys3_tb_behav xil_defaultlib.Basys3_tb -log elaborate.log

